In [1]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

In [4]:
np_height

array([1.87, 1.87, 1.82, 1.91, 1.9 , 1.85])

In [5]:
np_weight

array([81.65, 97.52, 95.25, 92.98, 86.18, 88.45])

In [2]:
print(type(np_height))

<class 'numpy.ndarray'>


In [3]:
# Calculate bmi
bmi = np_weight / np_height ** 2

# Print the result
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [12]:
# For a boolean response
bmi > 26

array([False,  True,  True, False, False, False])

In [10]:
# Print only those observations above 23
bmi[bmi > 26]

array([27.88755755, 28.75558507])