In [9]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# access to rows

In [32]:
for x in a:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]


# access to cells

## row order

In [33]:
for x in a.flat:
    print(x)


1
2
3
4
5
6
7
8
9


In [34]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

C order: row-based order is the default ordering

In [37]:
for x in np.nditer(a, order='C'):
    print(x)

1
2
3
4
5
6
7
8
9



## column order

Fortran order: column based order

In [38]:
for x in np.nditer(a, order='F'):
    print(x)

1
4
7
2
5
8
3
6
9


# split matrix horizontally and vertically

In [14]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [16]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

# indexing with boolean arrays

In [17]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [21]:
a[a>=10]

array([10, 11])

# replace numbers greater than or equal to 10 with -1

In [28]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
 a[a>=10] = -1

In [30]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, -1, -1]])

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])